version: "3"
services:
    rabbitmq3:
        hostname: rabbitmq
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
    identity-service:
        build:
            context: ./apps/identity
        ports:
            - "4000:4000"
        env_file:
            - ./apps/identity/.env
        depends_on:
            - rabbitmq3
    license-service:
        build:
            context: ./apps/license
        ports:
            - "5000:5000"
        env_file:
            - ./apps/identity/.env
    bankaccount-service:
        build:
            context: ./apps/bankaccount
        ports:
            - "6000:6000"
        depends_on:
            - rabbitmq3
        env_file:
            - ./apps/identity/.env
