version: "3"
services:
    rabbitmq:
        image: rabbitmq:3.10-rc-management-alpine
        ports:
      # AMQP protocol port
        - "5672:5672"
      # HTTP management UI
        - "15672:15672"

    identity-service:
        depends_on:
             - rabbitmq
        env_file:
            - ./apps/identity/.env
        build:
            context: ./apps/identity
        ports:
            - "4000:4000"
    license-service:
        depends_on:
             - rabbitmq
        env_file:
            - ./apps/identity/.env
        build:
            context: ./apps/license
        ports:
            - "5000:5000"
    bankaccount-service:
        depends_on:
             - rabbitmq
        env_file:
            - ./apps/identity/.env
        build:
            context: ./apps/bankaccount
        ports:
            - "6000:6000"
