apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankaccount-service-deployment
  labels:
    app: bankaccount-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankaccount-service
  template:
    metadata:
      labels:
        app: bankaccount-service
    spec:
      containers:
        - name: bankaccount-service-container
          image: europe-west4-docker.pkg.dev/smartspend/smart-spend/bankaccount:latest
          ports:
            - containerPort: 6001
          envFrom:
            - secretRef:
                name: cross-service-secrets
            - secretRef:
                name: bank-service-secrets
          resources:
            cpu: "500m"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "2Gi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bankaccount-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bankaccount-service-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
