apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankaccount-service
  labels:
    app: bankaccount-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankaccount-service
  template:
    metadata:
      labels:
        app: bankaccount-service
    spec:
      containers:
        - name: bankaccount-service-container
          image: europe-west4-docker.pkg.dev/smartspend/smart-spend/bank-account:latest
          ports:
            - containerPort: 6001
          envFrom:
            - secretRef:
                name: cross-service-secrets
            - secretRef:
                name: bank-service-secrets
          resources:
            limits:
              cpu: 0.5
              memory: "2Gi"
            requests:
              cpu: 0.5
              memory: "2Gi"

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bankaccount-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bankaccount-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 20

---

apiVersion: v1
kind: Service
metadata:
  name: bank-service-deployment
  namespace: default
spec:
  clusterIP: 10.14.128.3
  ports:
    - port: 80
      protocol: TCP
      targetPort: 6001
  selector:
    app: bankaccount-service
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.90.128.81