apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-deployment
  labels:
    app: identity-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service-container
          image: europe-west4-docker.pkg.dev/smartspend/smart-spend/identity:latest
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: production
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cross-service-secrets
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: cross-service-secrets
                  key: JWT_REFRESH_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: cross-service-secrets
                  key: JWT_EXPIRES_IN
            - name: JWT_REFRESH_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: cross-service-secrets
                  key: JWT_REFRESH_EXPIRES_IN
            - name: MONGO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cross-service-secrets
                  key: MONGO_DB_USER
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cross-service-secrets
                  key: MONGO_DB_PASSWORD
      volumes:
        - name: shared-secrets
          secret:
            secretName: cross-service-secrets
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: identity-service-deployment
  namespace: default
spec:
  targetRef:
    kind: Deployment
    name: identity-service-deployment
    apiVersion: apps/v1
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: identity-service-container
        mode: Auto
        controlledResources:
          - cpu
          - memory
        minAllowed: {}
        maxAllowed: {}
