apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-deployment
  labels:
    app: identity-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service-container
          image: europe-west4-docker.pkg.dev/smartspend/smart-spend/identity:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: cross-service-secrets
          resources:
            limits:
              cpu: 1
              memory: "512Mi"
            requests:
              cpu: 0.5
              memory: "256Mi"
      volumes:
        - name: shared-secrets
          secret:
            secretName: cross-service-secrets
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: identity-service-deployment
  namespace: default
spec:
  targetRef:
    kind: Deployment
    name: identity-service-deployment
    apiVersion: apps/v1
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: identity-service-container
        mode: Auto
        controlledResources:
          - cpu
          - memory
        minAllowed:
          cpu: 0.1
          memory: "64Mi"
        maxAllowed:
          cpu: 2
          memory: "1Gi"
