apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-service
  labels:
    app: license-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license-service
  template:
    metadata:
      labels:
        app: license-service
    spec:
      containers:
        - name: license-service-container
          image: europe-west4-docker.pkg.dev/smartspend/smart-spend/license:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: cross-service-secrets
          resources:
            limits:
              cpu: 1
              memory: "512Mi"
            requests:
              cpu: 0.5
              memory: "256Mi"

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: license-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: license-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50

---

apiVersion: v1
kind: Service
metadata:
  name: license-service-deployment
  namespace: default
spec:
  clusterIP: 10.14.128.4
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: license-service
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.90.128.83
