apiVersion: v1
kind: Service
metadata:
  name: bank-service-deployment
  namespace: default
spec:
  clusterIP: 10.14.128.3
  ports:
    - port: 80
      protocol: TCP
      targetPort: 6001
  selector:
    app: identity-service
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.90.128.81
