apiVersion: v1
kind: Service
metadata:
  name: identity-service-deployment
  namespace: default
spec:
  clusterIP: 10.25.2.172
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4000
  selector:
    app: identity-service
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.90.128.82
