apiVersion: v1
kind: Service
metadata:
  name: license-service-deployment
  namespace: default
spec:
  clusterIP: 10.14.128.4
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: license-service
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.90.128.83
