http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  identity:
    host: localhost
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
    paths: ["/auth/**"]
  bankAccount:
    host: localhost
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
    paths: ["/bank/**"]
  license:
    host: localhost
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
    paths: ["/license/**", "/company/**"]
serviceEndpoints:
  identity:
    url: http://identity-service:4000
  bankAccount:
    url: http://bankaccount-service:6001
  license:
    url: http://license-service:5000
policies:
  - proxy
  - log
pipelines:
  - name: identity
    apiEndpoints:
      - identity
    policies:
      - proxy:
          - action:
              serviceEndpoint: identity
              changeOrigin: true
  - name: bankAccount
    apiEndpoints:
      - bankAccount
    policies:
      - proxy:
          - action:
              serviceEndpoint: bankAccount
              changeOrigin: true
  - name: license
    apiEndpoints:
      - license
    policies:
      - proxy:
          - action:
              serviceEndpoint: license
              changeOrigin: true
