apiVersion: v1
kind: Service
metadata:
  name: identity-service-service
spec:
  type: NodePort
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
