name: CI 
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Build AuthService Dependencies
        run: |
          cd ./apps/identity 
          npm install
          npm install -g @nestjs/cli
          npm install typescript
          npm install @google-cloud/functions-framework
          npm run build
          
      - name: Install and Build BankAccountService Dependencies
        run: |
          cd ./apps/bankAccount 
          npm install
          npm install -g @nestjs/cli
          npm install typescript
          npm install @google-cloud/functions-framework
          npm run build
          
      - name: Install and Build LicenseService Dependencies
        run: |
          cd ./apps/license 
          npm install
          npm install -g @nestjs/cli
          npm install typescript
          npm install @google-cloud/functions-framework
          npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Test AuthService
        run: |
          cd ./apps/identity 
          npm install
          npm install -g @nestjs/cli
          npm install typescript
          npm install @google-cloud/functions-framework
          npm run test
          
      - name: Install and Test BankAccountService
        run: |
          cd ./apps/bankAccount 
          npm install
          npm install -g @nestjs/cli
          npm install typescript
          npm install @google-cloud/functions-framework
          npm run test
          
      - name: Install and Test LicenseService
        run: |
          cd ./apps/license 
          npm install
          npm install -g @nestjs/cli
          npm install typescript
          npm install @google-cloud/functions-framework
          npm run test
