name: CI 
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Test AuthService Dependencies
        run: |
          cd ./apps/auth 
          npm install
          npm install -g @nestjs/cli
          npm install -g @google-cloud/functions-framework
          npm run test
          
      - name: Install and Test BankAccountService Dependencies
        run: |
          cd ./apps/bankAccount 
          npm install
          npm install -g @nestjs/cli
          npm install -g @google-cloud/functions-framework
          npm run test
          
      - name: Install and Test LicenseService Dependencies
        run: |
          cd ./apps/license 
          npm install
          npm install -g @nestjs/cli
          npm install -g @google-cloud/functions-framework
          npm run test
