name: Deploy to GKE

on:
  push:
    branches: [gcloud-pipeline]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: smartspend
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use the gcloud command-line tool
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          cd apps/identity
          docker build -t europe-west4-docker.pkg.dev/smartspend/smart-spend/identity:latest -f Dockerfile .
          docker push europe-west4-docker.pkg.dev/smartspend/smart-spend/identity:latest

      - name: Configure kubectl
        run: |
          gcloud components install kubectl
          gcloud container clusters get-credentials smartspend-identity --zone europe-west4

      - name: Apply Kubernetes configuration
        run: |
          cd kubernetes/configs
          kubectl apply -f identity-config.yaml
