name: Deploy to GKE

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: smartspend
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use the gcloud command-line tool
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          cd ../../apps/identity
          docker build -t europe-west4-docker.pkg.dev/smartspend/smart-spend .
          docker push europe-west4-docker.pkg.dev/smartspend/smart-spend

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials smartspend-identity --zone europe-west4

      - name: Apply Kubernetes configuration
        run: |
          cd ../../kuberetes/configs/
          kubectl apply -f identity-config.yaml
