name: CI 
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Build AuthService Dependencies
        run: |
          cd ./apps/identity 
          npm install
          npm install -g @nestjs/cli
          npm install -g @google-cloud/functions-framework
          npm run build
          
      - name: Install and Build BankAccountService Dependencies
        run: |
          cd ./apps/bankAccount 
          npm install
          npm install -g @nestjs/cli
          npm install -g @google-cloud/functions-framework
          npm run build
          
      - name: Install and Build LicenseService Dependencies
        run: |
          cd ./apps/license 
          npm install
          npm install -g @nestjs/cli
          npm install -g @google-cloud/functions-framework
          npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Test AuthService
        run: |
          cd ./apps/identity 
          npm install
          npm install -g @nestjs/cli
          npm install -g @google-cloud/functions-framework
          npm run test
          
      - name: Install and Test BankAccountService
        run: |
          cd ./apps/bankAccount 
          npm install
          npm install -g @nestjs/cli
          npm install -g @google-cloud/functions-framework
          npm run test
          
      - name: Install and Test LicenseService
        run: |
          cd ./apps/license 
          npm install
          npm install -g @nestjs/cli
          npm install -g @google-cloud/functions-framework
          npm run test

  owasp:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OWASP ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Core.zip
          unzip ZAP_2.10.0_Core.zip
          export PATH=$PATH:$PWD/ZAP_2.10.0_Core

      - name: Scan AuthService with OWASP ZAP
        run: |
          zap-cli --zap-path $PWD/ZAP_2.10.0_Core -p 6000 -t http://localhost:6000/api/ -J report_auth.json -r report_auth.html -x report_auth.xml
      - name: Scan LicenseService with OWASP ZAP
        run: |
          zap-cli --zap-path $PWD/ZAP_2.10.0_Core -p 4000 -t http://localhost:4000/api/ -J report_auth.json -r report_auth.html -x report_auth.xml
      - name: Scan BankAccountService with OWASP ZAP
        run: |
          zap-cli --zap-path $PWD/ZAP_2.10.0_Core -p 5000 -t http://localhost:5000/api/ -J report_auth.json -r report_auth.html -x report_auth.xml
