name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: smartspend
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use the gcloud command-line tool
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/YOUR_PROJECT_ID/identity-service .
          docker push gcr.io/YOUR_PROJECT_ID/identity-service

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials YOUR_CLUSTER_NAME --zone YOUR_CLUSTER_ZONE

      - name: Apply Kubernetes configuration
        run: |
          kubectl apply -f path/to/your/kubernetes-config.yaml
