name: Deploy GKE

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: smartspend
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker image, Configure Docker to use gcloud, and Apply Kubernetes resources
        run: |
          if gcloud container clusters describe smartspend --zone europe-west4 &> /dev/null; then
          echo "Kubernetes cluster smartspend already exists. Skipping cluster creation."
          else
          gcloud components install kubectl
          gcloud container --project "smartspend" clusters create-auto "smartspend" --region "europe-west4" --release-channel "regular" --network "projects/smartspend/global/networks/default" --subnetwork "projects/smartspend/regions/europe-west4/subnetworks/default" --cluster-ipv4-cidr "/17" --services-ipv4-cidr "/22"
          fi

  deploy-identity:
    needs: create-cluster
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: smartspend
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push docker image
        run: |
          cd apps/identity
          gcloud auth configure-docker europe-west4-docker.pkg.dev
          docker build -t europe-west4-docker.pkg.dev/smartspend/smart-spend/identity:latest -f Dockerfile .
          docker push europe-west4-docker.pkg.dev/smartspend/smart-spend/identity:latest

      - name: Upload Kubernetes config
        run: |
          gcloud components install kubectl
          gcloud container clusters get-credentials smartspend --zone europe-west4
          cd kubernetes
          kubectl apply -f secrets/shared-secrets.yaml -f configs/identity-config.yaml

  deploy-bank:
    needs: create-cluster
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: smartspend
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push docker image
        run: |
          cd apps/bankAccount
          gcloud auth configure-docker europe-west4-docker.pkg.dev
          docker build -t europe-west4-docker.pkg.dev/smartspend/smart-spend/bank-account:latest -f Dockerfile .
          docker push europe-west4-docker.pkg.dev/smartspend/smart-spend/bank-account:latest

      - name: Upload Kubernetes config
        run: |
          gcloud components install kubectl
          gcloud container clusters get-credentials smartspend --zone europe-west4
          cd kubernetes
          kubectl apply -f secrets/shared-secrets.yaml -f secrets/bank-service-secrets.yaml -f configs/bankaccount-config.yaml

  deploy-license:
    needs: create-cluster
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: smartspend
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push docker image
        run: |
          cd apps/license
          gcloud auth configure-docker europe-west4-docker.pkg.dev
          docker build -t europe-west4-docker.pkg.dev/smartspend/smart-spend/license:latest -f Dockerfile .
          docker push europe-west4-docker.pkg.dev/smartspend/smart-spend/license:latest

      - name: Upload Kubernetes config
        run: |
          gcloud components install kubectl
          gcloud container clusters get-credentials smartspend --zone europe-west4
          cd kubernetes
          kubectl apply -f secrets/shared-secrets.yaml -f configs/license-config.yaml

