name: Deploy Gateway to GKE

on:
  workflow_dispatch:
  push:
    branches: [gcloud-pipeline]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: smartspend
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker image, Configure Docker to use gcloud, and Apply Kubernetes resources
        run: |
          cd apps/gateway
          gcloud auth configure-docker europe-west3-docker.pkg.dev
          docker build -t europe-west4-docker.pkg.dev/smartspend/smart-spend/gateway:latest -f Dockerfile .
          docker push europe-west4-docker.pkg.dev/smartspend/smart-spend/gateway:latest
          gcloud components install kubectl
          gcloud container clusters get-credentials smartspend-gateway --zone europe-west3
          cd ../../kubernetes
          kubectl apply -f configs/gateway-config.yaml -f loadbalancers/gateway-loadbalancer.yaml
